spring:
  application:
    name: lab1
  datasource:
    url: ${DB_URL:jdbc:h2:file:lab1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USER:haroun}
    password: ${DB_PASSWORD:passer}
  jpa:
    database-platform: ${DB_USER:org.hibernate.dialect.H2Dialect}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
  file:
    name: logs/logs.log


